# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Asaph Yuan
tagline:             Developer
url:                 http://asaphyuan.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Asaph Yuan
  url:               https://asaphyuan.com
  email:             asaph.yuan@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

#pages for nav
pages_list:       
  About: '/about'
  Archive: '/archive'
  Projects: '/projects'